# Generated by Django 5.1.3 on 2024-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_stock_alter_order_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
